### ISSUE TITLE
Breaks with latest patch from TODAY

### ISSUE THREAD

**Issue by methodbox** [trixnz/justfov#10]
Doesn't work with latest patch, big surprise. Thanks, Square.

**Comment by methodbox** [comment]
Based on two previous commits, it looks like this is what breaks every time:

```-        private readonly IntPtr _cameraManagerPtr = new IntPtr(0x142e72a58);
 -        private readonly IntPtr _setFovCall = new IntPtr(0x143229d70);
 +        //private readonly IntPtr _cameraManagerPtr = new IntPtr(0x142e72a58);
 +        //private readonly IntPtr _setFovCall = new IntPtr(0x143229d70);
 +
 +        //private const int CurrentCameraOffset = 0x5c0;
 +        //private const int CameraFlagsOffset = 0x55e;
 +        //private const int FovOffset1 = 0x580;
 +        //private const int FovOffset2 = 0x584;
```
and this is going to probably change with every update.

Instead of hard-coding this, you should instead query the value that is active, then set and use that to adjust FOV.

That should prevent it from breaking going forward.

If you have a hook to access the EXE when active, then you have the ability to pull the current hex value and set it dynamically.

**Comment by fordcars** [comment]
Sadly, I think it would be very difficult or virtually impossible to figure out which address would be the correct one without some complex algorithm or something :/

**Comment by methodbox** [comment]
The address is static with each update, it only changes when they roll an update.

The variable is the same every time; you're always manipulating the same camera value.

If you can view this in their source, then you can query it at runtime and return the current value, set your variable to this value and manipulate it as necessary.

The address variable that is targeted is static so there's no reason to update the code every time this changes.

**Comment by methodbox** [comment]
I don't know how this is done in C# but in JavaScript it would be like doing this:

var camera = document.getElementById('camera');

camera.innerHTML('new value');

Essentially, you're looking at the current value of an element, storing that in a variable, then redefining the variable and setting the element's value to the redefined value.

**Comment by Philpax** [comment]
That's not possible in this context. The addresses associated with native code must be manually reverse engineered each time the binary is updated.

**Comment by methodbox** [comment]
So, is anyone going to actually fix this? If I knew what language it was even in, or knew that language I'd do it myself, but I'm a JS guy.

**Comment by z2oh** [comment]
I spent a while looking for the values in memory but I didn't have any luck finding them. If someone has the game and hasn't updated to the latest patch, it wouldn't be hard to see exactly what values are being changed and then use that information to find the new values for the current patch.

**Comment by mumair85** [comment]
@z2oh I have worked on an issue #1 for justfov, can you direct me to a guide or some resources where I can learn how to find these values, I do have an older version so I might be able to help. Just need a starting point.

**Comment by z2oh** [comment]
@mumair85 If you know which patch you're on, you can use a memory viewer (Cheat Engine would probably work) to go to the address specified in the source. For example, the previous patch specified the memory address of the camera manager at 0x142F0CB58. If you run JC3 with this patch and look at the memory at that address, we can figure out what it is we are looking for exactly and then search for it on this patch.

**Comment by methodbox** [comment]
The two values needing to be manipulated will remain the same:
```
_cameraManagerPtr
_retRieVal
```
Those values are all we need to find, update and recompile.
However, I am not clear what language this is in - C#?

I'll try to hunt these down using that cheat engine tool a bit later. If someone would be so kind as to tell me anything the can about recompiling that'd be awesome.

I'll put in a PR when I get home.

**Comment by PsykomantaBrain** [comment]
It is C#, it should be simple enough to open the project in VS and rebuild it, if we know what to change.

If you can find the values with Cheat Engine, I can recompile the project here.

Cheers

**Comment by PsykomantaBrain** [comment]
I did some digging around with CE trying to find the new addresses, but assembly level coding is really not my area of expertise either... I did get the program to recompile here though... now all we need is the new mem addresses to point it to.

Cheers
