### ISSUE TITLE
Broken in latest update.

### ISSUE THREAD

**Issue by ruaraidheu** [trixnz/justfov#6]
The latest update of JC3 (2016-01-20) has stopped the tool from working.

**Comment by danvctr** [comment]
I second this motion.

**Comment by trixnz** [comment]
I am traveling and unavailable for a week, so unfortunately I won't be able to update it until next week.

**Comment by danvctr** [comment]
Guess we'll just have to wait... 😄

**Comment by rupertdance** [comment]
This would be great - thanks heaps trix.

**Comment by danvctr** [comment]
Thank you! Your program makes this game significantly more playable.
